#!/usr/bin/env bash
#A bash script that installs Nginx on my web01 server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
curl localhost
