#!/usr/bin/env bash
#Configures my Nginx server so that /redirect_me redirects to another page
path_conf="/etc/nginx/sites-available/default"
redirect="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}"
sed -i "48i$redirect" "$path_conf"
