#!/usr/bin/env bash
#Configure my Nginx server to have a custom 404 page
echo "Ceci n'est pas une page" > ERROR404.html
path_conf="/etc/nginx/sites-available/default"
redirect="\\\nerror_page 404 /ERROR404.html;\n"
sed -i "48i$redirect" "$path_conf"
