#!/usr/bin/env bash
#Configures Nginx so that its HTTP response contains a custom header X-Served-By: hostname
before="location \/ {"
after="add_header X-Served-By $(hostname)\;\n\n\tlocation \/ {"
path="/etc/nginx/sites-available/default"
sed -i "0,/$before/s|$before|$after|" "$path"
sudo service nginx restart
