#!/usr/bin/env bash
#Configures Nginx so that its HTTP response contains a custom header X-Served-By: hostname

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx start

path_conf="/etc/nginx/sites-available/default"
redirect="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}"
sed -i "48i$redirect" "$path_conf"

echo "Ceci n'est pas une page" | sudo tee /var/www/html/ERROR404.html > /dev/null
path_config="/etc/nginx/sites-available/default"
redirection="\\\n\terror_page 404 /ERROR404.html;\n"
sudo sed -i "48i$redirection" "$path_config"

before="location \/ {"
after="add_header X-Served-By $(hostname)\;\n\n\tlocation \/ {"
path="/etc/nginx/sites-available/default"
sed -i "0,/$before/s|$before|$after|" "$path"
sudo service nginx restart
