#!/usr/bin/env bash
#Configures ufw so that it blocks all incoming traffic, except the following TCP ports: 22, 443, 80
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
