#!/usr/bin/env bash
#A bash script that runs nginx as nginx

sudo chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo su nginx -s /bin/bash --command="service nginx restart"
